### ISSUE TITLE
Add fudge dice

### ISSUE THREAD

**Issue by saranvdev** [cro-ki/xdice#1]
Hey can you do this, please? :P
I would almost totally use your system then, because that dice pip package is so bad.

I mean something like
(f - fudge)
"1f10"
possible result: -10 to 10, i.e 7 0 2 -2 -6 10

**Comment by olinox14** [comment]
Yes, it could be done, what about a notation like 10df?

**Comment by olinox14** [comment]
Ok, that's done, let me know if that's what you wanted! I close this issue, I'll reopen it if needed.
