### ISSUE TITLE
Breaking in later Python versions

### ISSUE THREAD

**Issue by Remillard** [cro-ki/xdice#2]
I don't know exactly the cause, but I was tinkering with the package and going through your documented examples and ran across the following failure.  I suspect it's due to using latest Python release if I had to guess, but I haven't dug into it any deeper than this.
```
λ python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xdice
>>> ps = xdice.roll("2d6+18")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\xdice.py", line 27, in roll
    return Pattern(pattern_string).roll()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\xdice.py", line 318, in roll
    return PatternScore(self.format_string, scores)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\xdice.py", line 339, in __new__
    ps = super(PatternScore, cls).__new__(cls, _secured_eval(eval_string.format(*scores)))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\xdice.py", line 40, in _secured_eval
    return eval(raw, {"__builtins__":None}, _ALLOWED)
  File "<string>", line 1
    <Score; score=10; detail=[5, 5]; dropped=[]; name=2d6>+18
    ^
SyntaxError: invalid syntax
>>>
```

**Comment by Remillard** [comment]
Kind of weird though, if I dig through xdice.py and go to the lines noted in the traceback, they don't line up.  Line 339 in the is actually a blank line in the repo.  I did check and pip installed version 1.1.4 so I think it's the correct version but I can't explain the traceback and file incongruities.

**Comment by Remillard** [comment]
Well, best I can figure right now is that the string that's getting evaluated is using the __repr__ version of the Dice class, which includes all the interior components.  However I think eval just wants an algebra-like string so if you have 6d1 mathematically evaluate to "6" as an integer.  So perhaps Dice() class needs the __str__ method added to print the score variable and then when eval_string.format(*scores) is evaluated, it'll create the string `6+6` instead of `<Score; score=6; detail... name=6d1>+6`

However, I'm not an expert on subclassing, so maybe Python is supposed to be able to evaluate a class repr string and it's something else going on.

**Comment by Remillard** [comment]
Okay, giving Score() class a __str__ method seemed to fix things I think and your unit tests ran.  I'll submit a pull request.  In my fix I used f-strings because it was fast, but I'll convert that to older format style to match your code.

**Comment by olinox14** [comment]
You're right, the good fix is to reimplement the `__str__` method, since it appears that the `__str__` method of subclasses of `int` was removed : 

<https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior>
"Removed __str__ implementations from builtin types bool, int, float, complex and few classes from the standard library. They now inherit __str__() from object. As result, defining the __repr__() method in the subclass of these classes will affect their string representation."

We should'nt use f-strings for compatibility reasons with previous versions of python

**Comment by Remillard** [comment]
I'm glad there was a real reason that putting in `__str__` was the trick.  I hadn't found the note on int, just deduced that that eval string was going haywire.

And yes, I used f-strings initially because it was fast, but I'm pretty sure I altered it to older Python 3 style for the pull request.

**Comment by olinox14** [comment]
> And yes, I used f-strings initially because it was fast, but I'm pretty sure I altered it to older Python 3 style for the pull request.

Yep, you did :)
